import { useState, useEffect } from 'react'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../context/AuthContext'
import { jsPDF } from 'jspdf'

const STATUS_STYLES = {
  draft:    { bg: '#F3F4F6', text: '#6B7280' },
  sent:     { bg: '#EFF6FF', text: '#3B82F6' },
  accepted: { bg: '#ECFDF5', text: '#10B981' },
  declined: { bg: '#FEF2F2', text: '#EF4444' },
}

function generateProposalPDF(proposal, client, profile) {
  const doc = new jsPDF()
  const blue = [0, 66, 170]
  const dark = [10, 22, 40]
  const gray = [107, 114, 128]
  const lightGray = [243, 244, 246]

  // Header band
  doc.setFillColor(...blue)
  doc.rect(0, 0, 210, 36, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text(profile?.business_name || 'ConsultPro', 14, 16)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Business Proposal', 14, 27)

  // Title
  doc.setTextColor(...dark)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(proposal.title || 'Proposal', 14, 52)

  // Meta line
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...gray)
  const meta = [
    client?.name && `Client: ${client.name}`,
    proposal.valid_until && `Valid Until: ${new Date(proposal.valid_until).toLocaleDateString()}`,
    `Date: ${new Date(proposal.created_at || Date.now()).toLocaleDateString()}`,
  ].filter(Boolean).join('   ·   ')
  doc.text(meta, 14, 60)

  doc.setDrawColor(...blue)
  doc.setLineWidth(0.5)
  doc.line(14, 65, 196, 65)

  let y = 74

  const addSection = (title, content) => {
    if (!content?.trim()) return
    if (y > 255) { doc.addPage(); y = 20 }
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...blue)
    doc.text(title, 14, y)
    y += 7
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...dark)
    const lines = doc.splitTextToSize(content, 182)
    for (const line of lines) {
      if (y > 272) { doc.addPage(); y = 20 }
      doc.text(line, 14, y)
      y += 5
    }
    y += 6
  }

  addSection('Introduction', proposal.intro)
  addSection('Scope of Work', proposal.scope)
  addSection('Deliverables', proposal.deliverables)
  addSection('Timeline', proposal.timeline)

  // Pricing box
  if (proposal.amount > 0) {
    if (y > 240) { doc.addPage(); y = 20 }
    doc.setFillColor(...lightGray)
    doc.roundedRect(14, y, 182, 22, 3, 3, 'F')
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...dark)
    doc.text('Investment', 20, y + 9)
    doc.setFontSize(14)
    doc.setTextColor(...blue)
    doc.text(`$${Number(proposal.amount).toLocaleString()}`, 196, y + 9, { align: 'right' })
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...gray)
    doc.text('Total project fee', 20, y + 17)
    y += 30
  }

  addSection('Payment Terms', proposal.payment_terms)

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(...gray)
  doc.text('Generated by ConsultPro', 105, 287, { align: 'center' })

  doc.save(`Proposal_${client?.name || 'Client'}_${proposal.title || 'Draft'}.pdf`)
}

function ProposalForm({ clientId, userId, proposal, onSave, onCancel }) {
  const [form, setForm] = useState({
    title: proposal?.title || '',
    intro: proposal?.intro || '',
    scope: proposal?.scope || '',
    deliverables: proposal?.deliverables || '',
    timeline: proposal?.timeline || '',
    amount: proposal?.amount || '',
    payment_terms: proposal?.payment_terms || '',
    valid_until: proposal?.valid_until || '',
  })
  const [saving, setSaving] = useState(false)

  const set = (k) => (e) => setForm(f => ({ ...f, [k]: e.target.value }))

  const handleSave = async (e) => {
    e.preventDefault()
    setSaving(true)
    const payload = { ...form, amount: parseFloat(form.amount) || 0, user_id: userId, client_id: clientId, updated_at: new Date().toISOString() }
    let result
    if (proposal?.id) {
      result = await supabase.from('proposals').update(payload).eq('id', proposal.id).select().single()
    } else {
      result = await supabase.from('proposals').insert(payload).select().single()
    }
    setSaving(false)
    onSave(result.data)
  }

  const inputCls = 'w-full px-4 py-2.5 rounded-xl border border-gray-200 text-sm focus:outline-none focus:border-blue-300'
  const areaCls = `${inputCls} resize-none`
  const labelCls = 'block text-xs font-semibold text-gray-500 mb-1'

  return (
    <form onSubmit={handleSave} className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
      <h3 className="font-bold text-base mb-4" style={{ color: '#0A1628' }}>
        {proposal?.id ? 'Edit Proposal' : 'New Proposal'}
      </h3>
      <div className="space-y-4">
        <div>
          <label className={labelCls}>Title *</label>
          <input required value={form.title} onChange={set('title')} placeholder="e.g. Q2 Marketing Strategy Engagement" className={inputCls} />
        </div>
        <div>
          <label className={labelCls}>Introduction</label>
          <textarea value={form.intro} onChange={set('intro')} rows={3} placeholder="Brief overview of the engagement and why you're the right fit…" className={areaCls} />
        </div>
        <div>
          <label className={labelCls}>Scope of Work</label>
          <textarea value={form.scope} onChange={set('scope')} rows={4} placeholder="Detailed description of what will be done…" className={areaCls} />
        </div>
        <div>
          <label className={labelCls}>Deliverables</label>
          <textarea value={form.deliverables} onChange={set('deliverables')} rows={3} placeholder="List specific outputs and deliverables…" className={areaCls} />
        </div>
        <div>
          <label className={labelCls}>Timeline</label>
          <textarea value={form.timeline} onChange={set('timeline')} rows={2} placeholder="e.g. 8 weeks, starting May 1st…" className={areaCls} />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className={labelCls}>Investment ($)</label>
            <input type="number" min="0" step="0.01" value={form.amount} onChange={set('amount')} placeholder="0.00" className={inputCls} />
          </div>
          <div>
            <label className={labelCls}>Valid Until</label>
            <input type="date" value={form.valid_until} onChange={set('valid_until')} className={inputCls} />
          </div>
        </div>
        <div>
          <label className={labelCls}>Payment Terms</label>
          <textarea value={form.payment_terms} onChange={set('payment_terms')} rows={2} placeholder="e.g. 50% upfront, 50% on completion. Net 30." className={areaCls} />
        </div>
      </div>
      <div className="flex gap-3 mt-5">
        <button type="button" onClick={onCancel}
          className="flex-1 py-2.5 rounded-xl border border-gray-200 text-sm font-semibold text-gray-600 hover:bg-gray-50">
          Cancel
        </button>
        <button type="submit" disabled={saving}
          className="flex-1 py-2.5 rounded-xl text-white text-sm font-semibold disabled:opacity-50"
          style={{ background: '#0042AA' }}>
          {saving ? 'Saving…' : 'Save Proposal'}
        </button>
      </div>
    </form>
  )
}

export default function ProposalsTab({ clientId, client }) {
  const { user } = useAuth()
  const [proposals, setProposals] = useState([])
  const [loading, setLoading] = useState(true)
  const [showForm, setShowForm] = useState(false)
  const [editingProposal, setEditingProposal] = useState(null)
  const [profile, setProfile] = useState(null)
  const [sendingId, setSendingId] = useState(null)

  const load = async () => {
    const [pRes, profRes] = await Promise.all([
      supabase.from('proposals').select('*').eq('client_id', clientId).order('created_at', { ascending: false }),
      supabase.from('profiles').select('*').eq('id', user.id).single(),
    ])
    setProposals(pRes.data || [])
    setProfile(profRes.data)
    setLoading(false)
  }

  useEffect(() => { if (user && clientId) load() }, [user, clientId])

  const handleSave = (saved) => {
    setShowForm(false)
    setEditingProposal(null)
    load()
  }

  const updateStatus = async (id, status) => {
    const update = { status, updated_at: new Date().toISOString() }
    if (status === 'accepted') update.accepted_at = new Date().toISOString()
    await supabase.from('proposals').update(update).eq('id', id)
    load()
  }

  const deleteProposal = async (id) => {
    if (!confirm('Delete this proposal?')) return
    await supabase.from('proposals').delete().eq('id', id)
    load()
  }

  const sendProposal = async (proposal) => {
    if (!client?.email) {
      alert('This client has no email address on file. Add one in the Overview tab first.')
      return
    }
    setSendingId(proposal.id)
    try {
      // Generate email body from proposal
      const body = `
        <div style="font-family:sans-serif;max-width:600px;margin:0 auto;color:#1a1a2e">
          <div style="background:#0042AA;padding:24px 32px;border-radius:12px 12px 0 0">
            <h1 style="color:white;margin:0;font-size:22px">${profile?.business_name || 'ConsultPro'}</h1>
            <p style="color:#93c5fd;margin:4px 0 0;font-size:13px">Business Proposal</p>
          </div>
          <div style="padding:32px;background:#fff;border:1px solid #e5e7eb;border-radius:0 0 12px 12px">
            <h2 style="color:#0A1628;margin:0 0 8px">${proposal.title}</h2>
            <p style="color:#6B7280;font-size:13px;margin:0 0 24px">
              ${proposal.valid_until ? `Valid until ${new Date(proposal.valid_until).toLocaleDateString()}` : ''}
            </p>
            ${proposal.intro ? `<p style="color:#374151;line-height:1.6">${proposal.intro}</p>` : ''}
            ${proposal.scope ? `<h3 style="color:#0042AA;margin:20px 0 8px">Scope of Work</h3><p style="color:#374151;line-height:1.6;white-space:pre-line">${proposal.scope}</p>` : ''}
            ${proposal.deliverables ? `<h3 style="color:#0042AA;margin:20px 0 8px">Deliverables</h3><p style="color:#374151;line-height:1.6;white-space:pre-line">${proposal.deliverables}</p>` : ''}
            ${proposal.timeline ? `<h3 style="color:#0042AA;margin:20px 0 8px">Timeline</h3><p style="color:#374151">${proposal.timeline}</p>` : ''}
            ${proposal.amount > 0 ? `
              <div style="background:#F3F4F6;padding:20px 24px;border-radius:10px;margin:24px 0;display:flex;justify-content:space-between;align-items:center">
                <span style="font-weight:600;color:#0A1628">Total Investment</span>
                <span style="font-size:22px;font-weight:700;color:#0042AA">$${Number(proposal.amount).toLocaleString()}</span>
              </div>` : ''}
            ${proposal.payment_terms ? `<p style="color:#6B7280;font-size:13px">${proposal.payment_terms}</p>` : ''}
            <div style="margin-top:32px;padding-top:20px;border-top:1px solid #e5e7eb;text-align:center">
              <p style="color:#6B7280;font-size:12px">Questions? Reply to this email or contact us directly.</p>
            </div>
          </div>
        </div>`

      await supabase.functions.invoke('send-invoice', {
        body: {
          to: client.email,
          to_name: client.name,
          subject: `Proposal: ${proposal.title}`,
          body,
          from_name: profile?.business_name || 'ConsultPro',
        },
      })

      await supabase.from('proposals').update({
        status: 'sent',
        sent_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      }).eq('id', proposal.id)

      load()
    } catch (err) {
      console.error(err)
      alert('Failed to send proposal. Please check the client email address.')
    }
    setSendingId(null)
  }

  if (loading) return <div className="py-16 text-center text-gray-400 text-sm">Loading proposals…</div>

  return (
    <div>
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <p className="text-sm text-gray-500">Create, send, and track proposals for this client.</p>
        {!showForm && !editingProposal && (
          <button onClick={() => setShowForm(true)}
            className="px-4 py-2 rounded-xl text-white text-sm font-semibold"
            style={{ background: '#0042AA' }}>
            + New Proposal
          </button>
        )}
      </div>

      {/* New / edit form */}
      {(showForm || editingProposal) && (
        <div className="mb-5">
          <ProposalForm
            clientId={clientId}
            userId={user.id}
            proposal={editingProposal}
            onSave={handleSave}
            onCancel={() => { setShowForm(false); setEditingProposal(null) }}
          />
        </div>
      )}

      {/* Proposals list */}
      {proposals.length === 0 && !showForm ? (
        <div className="text-center py-20 bg-white rounded-2xl border border-gray-100 text-gray-400">
          <p className="text-3xl mb-2">📄</p>
          <p className="font-semibold">No proposals yet</p>
          <p className="text-sm mt-1">Click "New Proposal" to create your first one.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {proposals.map(p => {
            const sc = STATUS_STYLES[p.status] || STATUS_STYLES.draft
            return (
              <div key={p.id} className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
                <div className="flex items-start justify-between">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h3 className="font-bold text-sm" style={{ color: '#0A1628' }}>{p.title}</h3>
                      <span className="text-xs font-semibold px-2 py-0.5 rounded-full capitalize"
                        style={{ background: sc.bg, color: sc.text }}>{p.status}</span>
                    </div>
                    <div className="flex items-center gap-3 mt-1 text-xs text-gray-400 flex-wrap">
                      {p.amount > 0 && <span className="font-semibold" style={{ color: '#0042AA' }}>${Number(p.amount).toLocaleString()}</span>}
                      {p.valid_until && <span>Valid until {new Date(p.valid_until).toLocaleDateString()}</span>}
                      {p.sent_at && <span>Sent {new Date(p.sent_at).toLocaleDateString()}</span>}
                      {p.accepted_at && <span className="text-green-500">Accepted {new Date(p.accepted_at).toLocaleDateString()}</span>}
                    </div>
                    {p.intro && <p className="text-xs text-gray-400 mt-2 line-clamp-2">{p.intro}</p>}
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-2 ml-3 flex-shrink-0 flex-wrap justify-end">
                    <button onClick={() => generateProposalPDF(p, client, profile)}
                      className="text-xs px-3 py-1.5 rounded-lg font-semibold hover:opacity-80"
                      style={{ background: '#F3F4F6', color: '#374151' }}>
                      ↓ PDF
                    </button>

                    {p.status === 'draft' && (
                      <>
                        <button onClick={() => setEditingProposal(p)}
                          className="text-xs px-3 py-1.5 rounded-lg font-semibold hover:opacity-80"
                          style={{ background: '#EFF6FF', color: '#3B82F6' }}>
                          Edit
                        </button>
                        <button
                          onClick={() => sendProposal(p)}
                          disabled={sendingId === p.id}
                          className="text-xs px-3 py-1.5 rounded-lg font-semibold text-white hover:opacity-80 disabled:opacity-50"
                          style={{ background: '#0042AA' }}>
                          {sendingId === p.id ? 'Sending…' : '✉ Send'}
                        </button>
                      </>
                    )}

                    {p.status === 'sent' && (
                      <>
                        <button onClick={() => updateStatus(p.id, 'accepted')}
                          className="text-xs px-3 py-1.5 rounded-lg font-semibold hover:opacity-80"
                          style={{ background: '#ECFDF5', color: '#10B981' }}>
                          ✓ Accepted
                        </button>
                        <button onClick={() => updateStatus(p.id, 'declined')}
                          className="text-xs px-3 py-1.5 rounded-lg font-semibold hover:opacity-80"
                          style={{ background: '#FEF2F2', color: '#EF4444' }}>
                          ✗ Declined
                        </button>
                      </>
                    )}

                    <button onClick={() => deleteProposal(p.id)}
                      className="text-xs px-2 py-1.5 rounded-lg font-semibold hover:opacity-80 text-gray-300 hover:text-red-400">
                      ×
                    </button>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
