import { useEffect, useState, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import { jsPDF } from 'jspdf'
import ActivityFeed from '../components/ActivityFeed'
import TaskPanel from '../components/TaskPanel'

// ─── Assessment config ────────────────────────────────────────────────────────
const ASSESSMENTS = [
  { id: 'strategy',   label: 'Strategy & Planning',       icon: '🎯', color: '#0042AA', bg: '#EFF6FF' },
  { id: 'operations', label: 'Operational Efficiency',    icon: '⚙️', color: '#6366F1', bg: '#EEF2FF' },
  { id: 'financial',  label: 'Financial Performance',     icon: '💰', color: '#10B981', bg: '#ECFDF5' },
  { id: 'marketing',  label: 'Marketing & Sales',         icon: '📣', color: '#F59E0B', bg: '#FFFBEB' },
  { id: 'technology', label: 'Technology & Security',     icon: '🔐', color: '#8B5CF6', bg: '#F5F3FF' },
  { id: 'change',     label: 'Change Management',         icon: '🔄', color: '#EC4899', bg: '#FDF2F8' },
  { id: 'hr',         label: 'Human Resources',           icon: '👥', color: '#14B8A6', bg: '#F0FDFA' },
]

const STATUS_COLORS = {
  active:   { bg: '#ECFDF5', text: '#10B981' },
  inactive: { bg: '#F3F4F6', text: '#6B7280' },
  prospect: { bg: '#EEF2FF', text: '#6366F1' },
}

const SCORE_LABELS = ['', 'Critical', 'Needs Work', 'Developing', 'Good', 'Excellent']

// ─── Score badge ──────────────────────────────────────────────────────────────
function ScoreBadge({ score }) {
  if (!score) return null
  const colors = ['', '#EF4444', '#F59E0B', '#F59E0B', '#10B981', '#10B981']
  return (
    <span className="text-xs font-bold px-2.5 py-1 rounded-full text-white"
      style={{ background: colors[Math.round(score)] }}>
      {score}/5 · {SCORE_LABELS[Math.round(score)]}
    </span>
  )
}

// ─── PDF generator for completed assessment ───────────────────────────────────
function generateAssessmentPDF({ assessment, client, profile }) {
  const doc = new jsPDF()
  const blue = [0, 66, 170]
  const dark = [10, 22, 40]
  const gray = [107, 114, 128]
  const cfg = ASSESSMENTS.find(a => a.id === assessment.assessment_type) || ASSESSMENTS[0]

  // Header
  doc.setFillColor(...blue)
  doc.rect(0, 0, 210, 32, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(profile?.business_name || 'ConsultPro', 14, 14)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('AI Workflow Assessment Report', 14, 24)

  // Title block
  doc.setTextColor(...dark)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(`${cfg.icon} ${cfg.label}`, 14, 50)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...gray)
  doc.text(`Client: ${client?.name || '—'}`, 14, 60)
  doc.text(`Date: ${new Date(assessment.created_at).toLocaleDateString()}`, 14, 68)

  if (assessment.score) {
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...blue)
    doc.text(`Score: ${assessment.score}/5 · ${SCORE_LABELS[Math.round(assessment.score)]}`, 14, 78)
  }

  // Divider
  doc.setDrawColor(...blue)
  doc.setLineWidth(0.5)
  doc.line(14, 84, 196, 84)

  // Conversation transcript
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...dark)
  doc.text('Assessment Transcript', 14, 92)

  let y = 100
  const messages = assessment.messages || []
  for (const msg of messages) {
    const role = msg.role === 'assistant' ? 'Consultant AI' : 'You'
    const roleColor = msg.role === 'assistant' ? blue : dark
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...roleColor)
    doc.setFontSize(8)
    doc.text(role, 14, y)
    y += 5

    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...gray)
    const lines = doc.splitTextToSize(msg.content, 178)
    for (const line of lines) {
      if (y > 270) { doc.addPage(); y = 20 }
      doc.text(line, 14, y)
      y += 5
    }
    y += 3
  }

  // Footer
  doc.setTextColor(...gray)
  doc.setFontSize(8)
  doc.text('Generated by ConsultPro · AI Workflow Assessment', 105, 285, { align: 'center' })

  doc.save(`${client?.name || 'Client'}_${cfg.label}_Assessment.pdf`)
}

// ─── Chat message bubble ──────────────────────────────────────────────────────
function ChatBubble({ msg }) {
  const isUser = msg.role === 'user'
  return (
    <div className={`flex ${isUser ? 'justify-end' : 'justify-start'} mb-3`}>
      {!isUser && (
        <div className="w-7 h-7 rounded-full flex items-center justify-center mr-2 flex-shrink-0 mt-1"
          style={{ background: '#0042AA' }}>
          <span className="text-white text-xs font-bold">AI</span>
        </div>
      )}
      <div className={`max-w-[75%] px-4 py-3 rounded-2xl text-sm leading-relaxed ${
        isUser
          ? 'text-white rounded-br-sm'
          : 'text-gray-800 bg-white border border-gray-100 rounded-bl-sm shadow-sm'
      }`}
        style={isUser ? { background: '#0042AA' } : {}}>
        {msg.content.split('\n').map((line, i) => (
          <span key={i}>
            {line.split(/(\*\*[^*]+\*\*)/).map((part, j) =>
              part.startsWith('**') && part.endsWith('**')
                ? <strong key={j}>{part.slice(2, -2)}</strong>
                : part
            )}
            {i < msg.content.split('\n').length - 1 && <br />}
          </span>
        ))}
      </div>
    </div>
  )
}

// ─── Workflow Chat Modal ──────────────────────────────────────────────────────
function WorkflowChatModal({ assessmentType, client, existingAssessment, onClose, onSave, profile }) {
  const cfg = ASSESSMENTS.find(a => a.id === assessmentType)
  const [messages, setMessages] = useState(existingAssessment?.messages || [])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [score, setScore] = useState(existingAssessment?.score || null)
  const [status, setStatus] = useState(existingAssessment?.status || 'in_progress')
  const [assessmentId, setAssessmentId] = useState(existingAssessment?.id || null)
  const [saving, setSaving] = useState(false)
  const bottomRef = useRef(null)
  const { user } = useAuth()
  const { data: sessionData } = supabase.auth.getSession ? { data: null } : { data: null }

  // Kick off the first AI message if this is a new chat
  useEffect(() => {
    if (messages.length === 0) {
      startChat()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, loading])

  const getSession = async () => {
    const { data } = await supabase.auth.getSession()
    return data?.session?.access_token
  }

  const startChat = async () => {
    setLoading(true)
    const token = await getSession()
    try {
      const res = await supabase.functions.invoke('chat-assessment', {
        body: {
          messages: [{ role: 'user', content: `Start the ${cfg.label} assessment for my client: ${client?.name || 'the client'}. Begin with your first question.` }],
          assessment_type: assessmentType,
        },
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
      const aiText = res.data?.response || 'Hello! Let\'s begin the assessment. Tell me about your client\'s current situation.'
      const initMessages = [
        { role: 'user', content: `Start the ${cfg.label} assessment for ${client?.name || 'the client'}.` },
        { role: 'assistant', content: aiText },
      ]
      setMessages(initMessages)
      await persistAssessment(initMessages, null, 'in_progress')
    } catch (e) {
      console.error(e)
    }
    setLoading(false)
  }

  const persistAssessment = async (msgs, sc, st) => {
    const payload = {
      user_id: user.id,
      client_id: client?.id || null,
      assessment_type: assessmentType,
      title: `${cfg.label} — ${client?.name || 'General'}`,
      messages: msgs,
      score: sc,
      status: st || 'in_progress',
      updated_at: new Date().toISOString(),
    }
    if (assessmentId) {
      await supabase.from('workflow_assessments').update(payload).eq('id', assessmentId)
    } else {
      const { data } = await supabase.from('workflow_assessments').insert(payload).select().single()
      if (data) setAssessmentId(data.id)
    }
  }

  const sendMessage = async () => {
    if (!input.trim() || loading) return
    const userMsg = { role: 'user', content: input.trim() }
    const newMessages = [...messages, userMsg]
    setMessages(newMessages)
    setInput('')
    setLoading(true)

    const token = await getSession()
    try {
      const res = await supabase.functions.invoke('chat-assessment', {
        body: {
          messages: newMessages.map(m => ({ role: m.role, content: m.content })),
          assessment_type: assessmentType,
        },
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
      const aiText = res.data?.response || 'Thank you for that information. Could you tell me more?'
      const withAI = [...newMessages, { role: 'assistant', content: aiText }]
      setMessages(withAI)

      // Auto-extract score if AI mentions Score:
      const scoreMatch = aiText.match(/\*\*Score:\s*([\d.]+)\/5\*\*/)
      const extractedScore = scoreMatch ? parseFloat(scoreMatch[1]) : score

      await persistAssessment(withAI, extractedScore, 'in_progress')
      if (extractedScore) setScore(extractedScore)
    } catch (e) {
      console.error(e)
    }
    setLoading(false)
  }

  const completeAssessment = async () => {
    setSaving(true)
    await persistAssessment(messages, score, 'completed')
    setStatus('completed')
    onSave()
    setSaving(false)
  }

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl flex flex-col" style={{ height: '85vh' }}>
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-gray-100 flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center text-xl"
              style={{ background: cfg.bg }}>
              {cfg.icon}
            </div>
            <div>
              <h2 className="font-bold text-base" style={{ color: '#0A1628' }}>{cfg.label}</h2>
              <p className="text-xs text-gray-400">{client?.name || 'General Assessment'}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {score && <ScoreBadge score={score} />}
            {status === 'completed' && (
              <button
                onClick={() => generateAssessmentPDF({ assessment: { messages, score, assessment_type: assessmentType, created_at: new Date().toISOString() }, client, profile })}
                className="text-xs px-3 py-1.5 rounded-lg font-semibold"
                style={{ background: '#EFF6FF', color: '#0042AA' }}>
                ↓ PDF
              </button>
            )}
            {status === 'in_progress' && messages.length > 4 && (
              <button
                onClick={completeAssessment}
                disabled={saving}
                className="text-xs px-3 py-1.5 rounded-lg font-semibold text-white"
                style={{ background: '#10B981' }}>
                {saving ? 'Saving…' : '✓ Complete'}
              </button>
            )}
            <button onClick={onClose}
              className="text-gray-400 hover:text-gray-600 text-xl w-8 h-8 flex items-center justify-center rounded-lg hover:bg-gray-100">
              ×
            </button>
          </div>
        </div>

        {/* Chat body */}
        <div className="flex-1 overflow-y-auto p-5" style={{ background: '#F8FAFC' }}>
          {messages.map((msg, i) => <ChatBubble key={i} msg={msg} />)}
          {loading && (
            <div className="flex justify-start mb-3">
              <div className="w-7 h-7 rounded-full flex items-center justify-center mr-2 flex-shrink-0"
                style={{ background: '#0042AA' }}>
                <span className="text-white text-xs font-bold">AI</span>
              </div>
              <div className="bg-white border border-gray-100 rounded-2xl rounded-bl-sm px-4 py-3 shadow-sm">
                <div className="flex gap-1">
                  {[0, 1, 2].map(i => (
                    <div key={i} className="w-2 h-2 rounded-full bg-gray-300 animate-bounce"
                      style={{ animationDelay: `${i * 0.15}s` }} />
                  ))}
                </div>
              </div>
            </div>
          )}
          <div ref={bottomRef} />
        </div>

        {/* Input */}
        {status === 'in_progress' ? (
          <div className="p-4 border-t border-gray-100 flex-shrink-0">
            <div className="flex gap-2">
              <textarea
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Type your answer… (Enter to send)"
                rows={2}
                className="flex-1 px-4 py-2.5 rounded-xl border border-gray-200 text-sm resize-none focus:outline-none focus:border-blue-300"
              />
              <button
                onClick={sendMessage}
                disabled={!input.trim() || loading}
                className="px-4 py-2.5 rounded-xl text-white font-semibold text-sm disabled:opacity-40"
                style={{ background: '#0042AA' }}>
                Send
              </button>
            </div>
            <p className="text-xs text-gray-400 mt-2 text-center">
              Answer each question, then click <strong>Complete</strong> when the assessment is done.
            </p>
          </div>
        ) : (
          <div className="p-4 border-t border-gray-100 text-center flex-shrink-0">
            <p className="text-sm font-semibold text-green-600">✓ Assessment completed</p>
            <button
              onClick={() => generateAssessmentPDF({ assessment: { messages, score, assessment_type: assessmentType, created_at: new Date().toISOString() }, client, profile })}
              className="mt-2 text-sm px-4 py-2 rounded-xl font-semibold"
              style={{ background: '#0042AA', color: 'white' }}>
              Download PDF Report
            </button>
          </div>
        )}
      </div>
    </div>
  )
}

// ─── Main ClientDetail page ───────────────────────────────────────────────────
export default function ClientDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { user } = useAuth()

  const [client, setClient] = useState(null)
  const [assessments, setAssessments] = useState([])
  const [profile, setProfile] = useState(null)
  const [contacts, setContacts] = useState([])
  const [tab, setTab] = useState('overview')
  const [loading, setLoading] = useState(true)

  const [activeChat, setActiveChat] = useState(null)
  const [notes, setNotes] = useState('')
  const [savingNotes, setSavingNotes] = useState(false)

  // Contact form state
  const [showContactForm, setShowContactForm] = useState(false)
  const [contactForm, setContactForm] = useState({ first_name: '', last_name: '', email: '', phone: '', title: '', notes: '' })
  const [savingContact, setSavingContact] = useState(false)

  const load = async () => {
    const [cliRes, assRes, profRes, ccRes] = await Promise.all([
      supabase.from('clients').select('*').eq('id', id).single(),
      supabase.from('workflow_assessments').select('*').eq('client_id', id).order('updated_at', { ascending: false }),
      supabase.from('profiles').select('*').eq('id', user.id).single(),
      supabase.from('company_contacts').select('*, contact:contacts(*)').eq('company_id', id),
    ])
    setClient(cliRes.data)
    setNotes(cliRes.data?.notes || '')
    setAssessments(assRes.data || [])
    setProfile(profRes.data)
    setContacts(ccRes.data || [])
    setLoading(false)
  }

  const addContact = async (e) => {
    e.preventDefault()
    setSavingContact(true)
    // Create contact
    const { data: newContact } = await supabase.from('contacts').insert({ ...contactForm, user_id: user.id }).select().single()
    if (newContact) {
      // Link to company
      await supabase.from('company_contacts').insert({ company_id: id, contact_id: newContact.id, user_id: user.id })
    }
    setContactForm({ first_name: '', last_name: '', email: '', phone: '', title: '', notes: '' })
    setShowContactForm(false)
    setSavingContact(false)
    load()
  }

  const linkExistingContact = async (contactId) => {
    await supabase.from('company_contacts').insert({ company_id: id, contact_id: contactId, user_id: user.id })
    load()
  }

  const removeContact = async (ccId) => {
    await supabase.from('company_contacts').delete().eq('id', ccId)
    load()
  }

  useEffect(() => { if (user && id) load() }, [user, id])

  const saveNotes = async () => {
    setSavingNotes(true)
    await supabase.from('clients').update({ notes }).eq('id', id)
    setSavingNotes(false)
  }

  const openChat = (assessmentType) => {
    const existing = assessments.find(a => a.assessment_type === assessmentType && a.status === 'in_progress')
      || assessments.find(a => a.assessment_type === assessmentType)
    setActiveChat({ type: assessmentType, existing: existing || null })
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-32 text-gray-400">Loading client…</div>
    )
  }

  if (!client) {
    return (
      <div className="text-center py-32">
        <p className="text-gray-400 mb-4">Client not found.</p>
        <button onClick={() => navigate('/clients')} className="text-sm font-semibold" style={{ color: '#0042AA' }}>
          ← Back to Clients
        </button>
      </div>
    )
  }

  const sc = STATUS_COLORS[client.status] || STATUS_COLORS.active
  const completedCount = assessments.filter(a => a.status === 'completed').length
  const avgScore = assessments.filter(a => a.score).length
    ? (assessments.filter(a => a.score).reduce((s, a) => s + Number(a.score), 0) / assessments.filter(a => a.score).length).toFixed(1)
    : null

  const TABS = ['overview', 'contacts', 'activity', 'tasks', 'workflows', 'notes']

  return (
    <div>
      {/* Back nav */}
      <button onClick={() => navigate('/clients')}
        className="flex items-center gap-1.5 text-sm font-semibold mb-5 hover:opacity-70"
        style={{ color: '#0042AA' }}>
        ← Clients
      </button>

      {/* Client header */}
      <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100 mb-5">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 rounded-2xl flex items-center justify-center text-2xl font-bold text-white"
              style={{ background: '#0042AA' }}>
              {client.name[0].toUpperCase()}
            </div>
            <div>
              <h1 className="text-2xl font-bold" style={{ color: '#0A1628' }}>{client.name}</h1>
              {client.contact_name && <p className="text-gray-500">{client.contact_name}</p>}
              {client.industry && <p className="text-sm text-gray-400">{client.industry}</p>}
            </div>
          </div>
          <div className="flex flex-col items-end gap-2">
            <span className="text-xs font-semibold px-2.5 py-1 rounded-full" style={{ background: sc.bg, color: sc.text }}>
              {client.status}
            </span>
            <span className="text-xs text-gray-400">{client.billing_type}{client.hourly_rate ? ` · $${client.hourly_rate}/hr` : ''}</span>
          </div>
        </div>

        {/* Mini KPIs */}
        <div className="grid grid-cols-3 gap-4 mt-5 pt-5 border-t border-gray-100">
          {[
            { label: 'Assessments Done', value: completedCount },
            { label: 'Avg Score', value: avgScore ? `${avgScore}/5` : '—' },
            { label: 'In Progress', value: assessments.filter(a => a.status === 'in_progress').length },
          ].map(({ label, value }) => (
            <div key={label} className="text-center">
              <p className="text-xs font-semibold text-gray-400">{label}</p>
              <p className="text-xl font-bold mt-0.5" style={{ color: '#0042AA' }}>{value}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 mb-5 bg-white rounded-xl p-1 shadow-sm border border-gray-100 w-fit">
        {TABS.map(t => (
          <button key={t} onClick={() => setTab(t)}
            className="px-5 py-2 rounded-lg text-sm font-semibold capitalize transition-all"
            style={tab === t
              ? { background: '#0042AA', color: 'white' }
              : { color: '#6B7280' }}>
            {t}
          </button>
        ))}
      </div>

      {/* ── Overview tab ─────────────────────────────────────────────────── */}
      {tab === 'overview' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
            <h3 className="font-bold text-sm mb-3" style={{ color: '#0A1628' }}>Contact Details</h3>
            <div className="space-y-2 text-sm text-gray-600">
              {client.email && <p>✉️ <a href={`mailto:${client.email}`} className="hover:underline" style={{ color: '#0042AA' }}>{client.email}</a></p>}
              {client.phone && <p>📞 {client.phone}</p>}
              {client.address && <p>📍 {client.address}</p>}
              {client.contact_name && <p>👤 {client.contact_name}</p>}
            </div>
          </div>
          <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
            <h3 className="font-bold text-sm mb-3" style={{ color: '#0A1628' }}>Recent Assessments</h3>
            {assessments.length === 0 ? (
              <p className="text-sm text-gray-400">No assessments yet. Go to the Workflows tab to start one.</p>
            ) : (
              <div className="space-y-2">
                {assessments.slice(0, 5).map(a => {
                  const cfg = ASSESSMENTS.find(x => x.id === a.assessment_type)
                  return (
                    <div key={a.id} className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <span className="text-base">{cfg?.icon}</span>
                        <span className="text-sm text-gray-700">{cfg?.label}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        {a.score && <ScoreBadge score={a.score} />}
                        <span className="text-xs px-2 py-0.5 rounded-full"
                          style={a.status === 'completed'
                            ? { background: '#ECFDF5', color: '#10B981' }
                            : { background: '#EFF6FF', color: '#3B82F6' }}>
                          {a.status}
                        </span>
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </div>
        </div>
      )}

      {/* ── Contacts tab ──────────────────────────────────────────────────── */}
      {tab === 'contacts' && (
        <div>
          <div className="flex items-center justify-between mb-4">
            <p className="text-sm text-gray-500">People linked to this company. Contacts can be linked to multiple companies.</p>
            <button onClick={() => setShowContactForm(v => !v)}
              className="px-4 py-2 rounded-xl text-white text-sm font-semibold"
              style={{ background: '#0042AA' }}>
              + Add Contact
            </button>
          </div>

          {/* Add contact form */}
          {showContactForm && (
            <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100 mb-4">
              <h3 className="font-bold text-sm mb-3" style={{ color: '#0A1628' }}>New Contact</h3>
              <form onSubmit={addContact} className="space-y-3">
                <div className="grid grid-cols-2 gap-3">
                  <input required placeholder="First name *" value={contactForm.first_name}
                    onChange={e => setContactForm(f => ({ ...f, first_name: e.target.value }))}
                    className="px-4 py-2.5 rounded-xl border border-gray-200 text-sm" />
                  <input placeholder="Last name" value={contactForm.last_name}
                    onChange={e => setContactForm(f => ({ ...f, last_name: e.target.value }))}
                    className="px-4 py-2.5 rounded-xl border border-gray-200 text-sm" />
                  <input type="email" placeholder="Email" value={contactForm.email}
                    onChange={e => setContactForm(f => ({ ...f, email: e.target.value }))}
                    className="px-4 py-2.5 rounded-xl border border-gray-200 text-sm" />
                  <input placeholder="Phone" value={contactForm.phone}
                    onChange={e => setContactForm(f => ({ ...f, phone: e.target.value }))}
                    className="px-4 py-2.5 rounded-xl border border-gray-200 text-sm" />
                  <input placeholder="Title / Role" value={contactForm.title}
                    onChange={e => setContactForm(f => ({ ...f, title: e.target.value }))}
                    className="col-span-2 px-4 py-2.5 rounded-xl border border-gray-200 text-sm" />
                </div>
                <textarea placeholder="Notes" rows={2} value={contactForm.notes}
                  onChange={e => setContactForm(f => ({ ...f, notes: e.target.value }))}
                  className="w-full px-4 py-2.5 rounded-xl border border-gray-200 text-sm resize-none" />
                <div className="flex gap-3">
                  <button type="button" onClick={() => setShowContactForm(false)}
                    className="flex-1 py-2 rounded-xl border border-gray-200 text-sm font-semibold text-gray-600">
                    Cancel
                  </button>
                  <button type="submit" disabled={savingContact}
                    className="flex-1 py-2 rounded-xl text-white text-sm font-semibold disabled:opacity-50"
                    style={{ background: '#0042AA' }}>
                    {savingContact ? 'Saving…' : 'Add Contact'}
                  </button>
                </div>
              </form>
            </div>
          )}

          {/* Contacts list */}
          {contacts.length === 0 ? (
            <div className="text-center py-16 text-gray-400 bg-white rounded-2xl border border-gray-100">
              No contacts linked yet. Add a contact above.
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
              {contacts.map(cc => {
                const c = cc.contact
                if (!c) return null
                return (
                  <div key={cc.id} className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
                    <div className="flex items-start justify-between mb-3">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl flex items-center justify-center font-bold text-white text-sm flex-shrink-0"
                          style={{ background: '#0042AA' }}>
                          {c.first_name?.[0]}{c.last_name?.[0]}
                        </div>
                        <div>
                          <p className="font-bold text-sm" style={{ color: '#0A1628' }}>
                            {c.first_name} {c.last_name}
                          </p>
                          {c.title && <p className="text-xs text-gray-400">{c.title}</p>}
                        </div>
                      </div>
                      <button onClick={() => removeContact(cc.id)}
                        className="text-gray-300 hover:text-red-400 text-lg leading-none">×</button>
                    </div>
                    <div className="space-y-1 text-sm">
                      {c.email && (
                        <p className="text-gray-500">
                          <a href={`mailto:${c.email}`} className="hover:underline" style={{ color: '#0042AA' }}>
                            ✉ {c.email}
                          </a>
                        </p>
                      )}
                      {c.phone && (
                        <p className="text-gray-500">
                          <a href={`tel:${c.phone}`}>📞 {c.phone}</a>
                          {' '}
                          <a href={`sms:${c.phone}`} className="text-xs ml-1" style={{ color: '#10B981' }}>💬 Text</a>
                        </p>
                      )}
                    </div>
                    {c.notes && <p className="text-xs text-gray-400 mt-2 pt-2 border-t border-gray-100">{c.notes}</p>}
                  </div>
                )
              })}
            </div>
          )}
        </div>
      )}

      {/* ── Activity tab ──────────────────────────────────────────────────── */}
      {tab === 'activity' && (
        <ActivityFeed companyId={id} />
      )}

      {/* ── Tasks tab ─────────────────────────────────────────────────────── */}
      {tab === 'tasks' && (
        <TaskPanel companyId={id} />
      )}

      {/* ── Workflows tab ─────────────────────────────────────────────────── */}
      {tab === 'workflows' && (
        <div>
          <p className="text-sm text-gray-500 mb-4">Click an assessment to start or resume an AI-guided session.</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4">
            {ASSESSMENTS.map(cfg => {
              const done = assessments.find(a => a.assessment_type === cfg.id && a.status === 'completed')
              const inProg = assessments.find(a => a.assessment_type === cfg.id && a.status === 'in_progress')
              return (
                <button key={cfg.id}
                  onClick={() => openChat(cfg.id)}
                  className="text-left bg-white rounded-2xl p-5 shadow-sm border border-gray-100 hover:shadow-md hover:border-blue-200 transition-all">
                  <div className="flex items-start justify-between mb-3">
                    <div className="w-12 h-12 rounded-xl flex items-center justify-center text-2xl"
                      style={{ background: cfg.bg }}>
                      {cfg.icon}
                    </div>
                    {done && <ScoreBadge score={done.score} />}
                    {!done && inProg && (
                      <span className="text-xs font-semibold px-2 py-1 rounded-full"
                        style={{ background: '#EFF6FF', color: '#3B82F6' }}>In Progress</span>
                    )}
                  </div>
                  <h3 className="font-bold text-sm mb-1" style={{ color: '#0A1628' }}>{cfg.label}</h3>
                  <p className="text-xs text-gray-400">
                    {done ? `Completed · Score ${done.score}/5`
                      : inProg ? 'Resume conversation'
                        : 'Start AI assessment'}
                  </p>
                </button>
              )
            })}
          </div>

          {/* Past assessments list */}
          {assessments.length > 0 && (
            <div className="mt-8">
              <h3 className="font-bold text-sm mb-3" style={{ color: '#0A1628' }}>All Assessment History</h3>
              <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-gray-100">
                      {['Type', 'Status', 'Score', 'Date', 'Actions'].map(h => (
                        <th key={h} className="text-left py-3 px-4 text-xs font-bold text-gray-400 uppercase">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {assessments.map(a => {
                      const cfg = ASSESSMENTS.find(x => x.id === a.assessment_type)
                      return (
                        <tr key={a.id} className="border-b border-gray-50 hover:bg-gray-50">
                          <td className="py-3 px-4 text-sm font-semibold" style={{ color: '#0A1628' }}>
                            {cfg?.icon} {cfg?.label}
                          </td>
                          <td className="py-3 px-4">
                            <span className="text-xs font-semibold px-2 py-1 rounded-full"
                              style={a.status === 'completed'
                                ? { background: '#ECFDF5', color: '#10B981' }
                                : { background: '#EFF6FF', color: '#3B82F6' }}>
                              {a.status}
                            </span>
                          </td>
                          <td className="py-3 px-4">
                            {a.score ? <ScoreBadge score={a.score} /> : <span className="text-xs text-gray-400">—</span>}
                          </td>
                          <td className="py-3 px-4 text-xs text-gray-400">
                            {new Date(a.updated_at).toLocaleDateString()}
                          </td>
                          <td className="py-3 px-4">
                            <div className="flex gap-2">
                              <button onClick={() => setActiveChat({ type: a.assessment_type, existing: a })}
                                className="text-xs px-2 py-1 rounded-lg font-semibold hover:opacity-80"
                                style={{ background: '#EFF6FF', color: '#3B82F6' }}>
                                {a.status === 'in_progress' ? 'Resume' : 'View'}
                              </button>
                              {a.status === 'completed' && (
                                <button
                                  onClick={() => generateAssessmentPDF({ assessment: a, client, profile })}
                                  className="text-xs px-2 py-1 rounded-lg font-semibold hover:opacity-80"
                                  style={{ background: '#F0FDF4', color: '#10B981' }}>
                                  PDF
                                </button>
                              )}
                            </div>
                          </td>
                        </tr>
                      )
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      )}

      {/* ── Notes tab ─────────────────────────────────────────────────────── */}
      {tab === 'notes' && (
        <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
          <div className="flex items-center justify-between mb-3">
            <h3 className="font-bold text-sm" style={{ color: '#0A1628' }}>Client Notes</h3>
            <button onClick={saveNotes} disabled={savingNotes}
              className="text-xs px-3 py-1.5 rounded-lg font-semibold text-white disabled:opacity-50"
              style={{ background: '#0042AA' }}>
              {savingNotes ? 'Saving…' : 'Save Notes'}
            </button>
          </div>
          <textarea
            value={notes}
            onChange={e => setNotes(e.target.value)}
            placeholder="Add notes about this client — meeting summaries, key decisions, follow-ups…"
            className="w-full px-4 py-3 rounded-xl border border-gray-200 text-sm resize-none focus:outline-none focus:border-blue-300"
            rows={16}
          />
        </div>
      )}

      {/* Chat modal */}
      {activeChat && (
        <WorkflowChatModal
          assessmentType={activeChat.type}
          client={client}
          existingAssessment={activeChat.existing}
          profile={profile}
          onClose={() => setActiveChat(null)}
          onSave={() => { load(); setActiveChat(null) }}
        />
      )}
    </div>
  )
}
